//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фотограф
    {
        public int Код_фотографа { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Стаж { get; set; }
        public string Опыт_работы { get; set; }
        public string Телефон { get; set; }
    }
}
